
parameters:
    doctrine.entity_file_paths: ["vendor/jdart/reddit2twitter/src/JDart/Reddit2Twitter/Entity"]

services:
    entity_manager.configuration: 
        class:          Doctrine\ORM\Configuration
        factory_class:  Doctrine\ORM\Tools\Setup
        factory_method: createAnnotationMetadataConfiguration
        arguments:      ["%doctrine.entity_file_paths%", "%debug%"]
    entity_manager:
        class:          Doctrine\ORM\EntityManager
        factory_class:  Doctrine\ORM\EntityManager
        factory_method: create
        arguments:      ["%doctrine.connection%", "@entity_manager.configuration"]
    cli_application:
        class:          Symfony\Component\Console\Application
        calls:
            - [add, ["@update_task"]]
    update_task:
        class:          JDart\Reddit2Twitter\Command\UpdateCommand 
        calls:
            - [setContainer, ["@service_container"]]
    reddit_client_factory:
        class:          Reddit\Api\Client\Factory
    reddit_client:
        class:          Reddit\Api\Client
        factory_class:  JDart\Reddit2Twitter\Setup\ClientFactory
        factory_method: getAuthorizedRedditClient
        arguments:
            - "@reddit_client_factory"
            - "%reddit.credentials%"
    twitter_oauth:
        class: tmhOAuth
        arguments: ["%twitter.credentials%"]
    twitter_rules:
        class: JDart\Reddit2Twitter\Twitter\GetTwitterRules
        arguments: ["%twitter.cache_dir%", "%twitter.cache_lifetime%", "@twitter_oauth"] 
    twitter_tweet:
        class:    JDart\Reddit2Twitter\Twitter\CreateTweetFromRedditPost
        arguments: ["@twitter_oauth", "@twitter_rules"]