
parameters:
    doctrine.entity_file_paths: ["vendor/jdart/reddit2twitter/src/JDart/Reddit2Twitter/Entity"]

services:
    entity_manager.configuration: 
        class:          Doctrine\ORM\Configuration
        factory_class:  Doctrine\ORM\Tools\Setup
        factory_method: createAnnotationMetadataConfiguration
        arguments:      ["%doctrine.entity_file_paths%", "%debug%"]
    entity_manager:
        class:          Doctrine\ORM\EntityManager
        factory_class:  Doctrine\ORM\EntityManager
        factory_method: create
        arguments:      ["%doctrine.connection%", "@entity_manager.configuration"]
    cli_application:
        class:          Symfony\Component\Console\Application
        calls:
            - [add, ["@cron_command"]]
    cron_command:
        class:          JDart\Reddit2Twitter\Command\CronCommand 
        calls:
            - [setContainer, ["@service_container"]]
    reddit.client:
        class:          JDart\Reddit2Twitter\Reddit\ClientH2S
        calls:
            - [configure, ["%reddit.credentials%"]]
    twitter.client:
        class:          JDart\Reddit2Twitter\Twitter\ClientTmhOauth
        calls:
            - [configure, ["%twitter.credentials%"]]
    twitter.rules:
        class:          JDart\Reddit2Twitter\Twitter\Rules
        arguments:      ["%paths.app%/%twitter.cache_dir%", "%twitter.cache_lifetime%", "@twitter.client"] 
    r2t_task.tweet_item:
        class:          JDart\Reddit2Twitter\Task\TweetItem
        arguments:      ["@twitter.client", "@twitter.rules"]
    r2t_task.queue_items:
        class:          JDart\Reddit2Twitter\Task\QueueItems
        arguments:      ["@entity_manager", "@reddit.client"]
    r2t_task.tweet_queued_items:
        class:          JDart\Reddit2Twitter\Task\TweetQueuedItems
        arguments:      ["@entity_manager", "@r2t_task.tweet_item"]